require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - vendor/**/*
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedRocketStyle: key
# Layout/IndentationStyle:
#   EnforcedStyle: tabs
Metrics/BlockLength:
  Max: 250
Metrics/ClassLength:
  Max: 250
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
