name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: default
        bundler-cache: true
    - name: Rubocop check
      run: |
        bundle exec rubocop
    - name: Run tests
      run: |
        bundle exec rake test
